[project]
name = "tarash-scene-detector"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ritesh Kadmawala", email = "ritesh@vertexcover.io" }
]
requires-python = ">=3.14"
dependencies = [
    "scenedetect[opencv]>=0.6.7.1",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
fallback-version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = ["src/tarash"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/README.md",
]
